SecureFileShare/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    # Examples:
    # url(r'^$', 'SecureFileShare.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^fileshare/',include('fileshare.urls', namespace="fileshare")),
    url(r'^',include('fileshare.urls')),
    url(r'^accounts/profile',RedirectView.as_view(url='/main')),
    #url(r'^',include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileshare/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib.auth import forms
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView
from fileshare.forms import LoginForm
from .forms import signup_form, UpdateProfile


# user authentication urls
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url('^register/signup',views.register,name='register'),
    url('^register/signup',CreateView.as_view(template_name='fileshare/register.html',form_class=signup_form,success_url='/fileshare/register/success')),
    url('^register/success',views.register_success,name='register_success'),
    url('^register/updateprofile/success',views.account_update_success,name='account_update_success'),
    url('^login/$',auth_views.login,{'template_name': 'fileshare/login.html', 'authentication_form': LoginForm},name='login'),
    url('^main',views.main,name='main'),
    url('^account/view',views.account,name='account'),
    url('^account/update',views.update_profile,name='accountupdate'),
    url('^account/changepassword',views.password_change,name='password_change'),
    url('^messages',views.messages, name='messages'),
    url('^create_report',views.create_report,name='create_report'),
    url(r'^user_delete_report/(?P<report_id>[0-9]+)$', views.user_delete_report, name='user_delete_report'),
    url('^create_group', views.create_group, name='create_group'),
    #url('^account/changepassword',auth_views.password_change,{'template_name':'fileshare/changepassword.html'},name='password_change'),
    #url('^account/changepassworddone',auth_views.password_change,{'template_name':'fileshare/changepassword.html'},name='password_change'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}),
    #url('^test', CreateView.as_view(template_name='fileshare/test.html',form_class=signup_form,success_url='/fileshare/register/success')),
    #url(r'^test',views.signin,name='signin'),
    #url(r'^',include('django.contrib.auth.urls')),
    url('^test', views.test, name='test'),
    url(r'^(?P<report_id>[0-9]+)/view/$', views.view_report, name='view_report'),
    url(r'^view_report/(?P<report_id>[0-9]+)$', views.view_report, name='view_report'),
    url(r'^view_group_report/(?P<report_id>[0-9]+)/(?P<profilegroup_id>[0-9]+)$', views.view_group_report, name='view_group_report'),
    url(r'^(?P<group_id>[0-9]+)/view_group/$', views.view_group, name='view_group'),
    url(r'^(?P<folder_id>[0-9]+)/view_folder/$', views.view_folder, name='view_folder'),
    url('^test', views.update_profile,name='updateprofile'),
    url('^deletemessage/(?P<message_pk>.*)$',views.deletemessage,name="delete_message"),
    #site manager urls
    url('^sitemanager',views.sitemanager, name='sitemanager'),
    url('^manage_users',views.manage_users, name='manage_users'),
    url('^manage_reports', views.manage_reports, name='manage_reports'),
    url('^manage_groups', views.manage_groups, name='manage_groups'),
    url('^edit_user/(?P<user_id>[0-9]+)', views.edit_user, name='edit_user'),
    url('^edit_user', views.edit_user, name='edit_user'),
    url('^sm_update_user', views.sm_update_user, name='sm_update_user'),
    url('^user_update_success.html', views.sm_update_user, name = 'user_update_success'),
    url(r'^delete_report/(?P<report_id>[0-9]+)$', views.delete_report, name='delete_report'),
    url('^decrypt_message/(?P<message_pk>.*)$',views.decrypt_message,name="decrypt_message"),
    url('^update_unread/(?P<message_pk>.*)$',views.updateunread,name="update_unread"),
    url('^search_results', views.search_results, name='search_results'),
    url('^fda_login/(?P<username>.+)/(?P<password>.+)', views.fda_login, name='fda_login'),
    url('^fda_getreports/(?P<username>.+)/(?P<password>.+)', views.fda_getreports, name='fda_getreports'),
    url('^fda_report_files/(?P<report_id>[0-9]+)$', views.fda_report_files, name='fda_report_files'),
]

fileshare/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    # Django automatically creates a primary key ID... No need to create one here

    user = models.OneToOneField(User)
    reports_owned = models.ManyToManyField('Report', blank=True)
    groups_in = models.ManyToManyField('ProfileGroup', blank=True)
    publickey = models.CharField(null=True, max_length=10000)
    unreadmessages = models.CharField(max_length=10, default="false")

    def __str__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)


# Create Reports model
class Report(models.Model):
    owned_by = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now_add=True, null=True)
    last_modified_by = models.CharField(default="Owner", max_length=128)
    short_desc = models.CharField("Title", max_length=128, unique=True)
    long_desc = models.TextField("Description")
    private = models.BooleanField("Restrict access to this file?", default=False)
    files = models.ManyToManyField('Documents', blank=True)
    is_encrypted = models.BooleanField("Is the attached file encrypted?", default=False,
                                       help_text="Leave blank if no file is attached.")
    in_folder = models.BooleanField(default=False)
    group_in = models.ManyToManyField('ProfileGroup', blank=True)
    comments = models.ManyToManyField('ReportComments', blank=True)

    def __str__(self):
        return self.short_desc


class Documents(models.Model):
    datetime = '%Y/%m/%d'
    file_attached = models.FileField("Upload a file", upload_to='reports/' + datetime, blank=True, null=True)
    is_encrypted = models.BooleanField(default=False)
    file_hash = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return str(self.file_attached)


class Folder(models.Model):
    name = models.CharField(max_length=128, unique=True)
    owned_by = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    reports = models.ManyToManyField(Report, blank=True)


class ProfileGroup(models.Model):
    creator = models.ForeignKey(User, null=True)
    name = models.CharField(max_length=128, unique=True)
    members = models.ManyToManyField('Profile', related_name='group_members', blank=True)
    reports = models.ManyToManyField('Report', blank=True)
    comments = models.ManyToManyField('ReportComments', blank=True)

    def __str__(self):
        return self.name


class Conversation(models.Model):
    sender = models.ForeignKey(User, related_name="sender")
    reciever = models.ForeignKey(User, related_name="reciever")
    reciever_name = models.CharField(max_length=128)
    recently_used = models.DateTimeField()
    messages = models.ManyToManyField('Message', blank=True)
    unreadmessages = models.CharField(max_length=1000, default="0")

    def __str__(self):
        return self.reciever_name


class Message(models.Model):
    owned_by = models.ForeignKey('Conversation')
    sender = models.ForeignKey(User)
    time = models.DateTimeField(auto_now_add=True)
    messagecontent = models.CharField(max_length=10000)
    key = models.CharField(null=True, max_length=10000)

    def __str__(self):
        return self.messagecontent


class Activity(models.Model):
    owned_by = models.ForeignKey(User)
    time = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=10000)


class ReportComments(models.Model):
    creator = models.ForeignKey('Profile')
    comment = models.TextField(max_length=1000, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

fileshare/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import validate_email
from fileshare.models import *
from Crypto.PublicKey import RSA
from Crypto import Random
from django import forms
from django.forms.extras.widgets import SelectDateWidget
import os

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))
"""
class signup_form(forms.ModelForm):

    A form that creates a user, with no privileges, from the given username and
    password.

    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
        'incorrect_email': ("The email address entered is incorrect"),
    }
    #email = forms.CharField(label= _("Email"),widget=forms.TextInput)

    password1 = forms.CharField(label=("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("username","email","first_name","last_name",)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not validate_email(email):
            raise forms.ValidationError(self.error_messages['incorrect_email'],code='incorrect_email')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(signup_form, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        privatekey = None
        if commit:
            user.save()
            random_generator = Random.new().read
            key = RSA.generate(1024, random_generator)
            pubkey = key.publickey()
            privatekey = key.privatekey()
            user.profile.publickey = pubkey
        return user
"""
class signup_form(forms.ModelForm):
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
        'incorrect_email': ("The email address entered is incorrect"),
    }
    #email = forms.CharField(label= _("Email"),widget=forms.TextInput)

    password1 = forms.CharField(label=("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("username","email","first_name","last_name",)


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        """
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
            """
        return (password1 and password2 and password1 != password2)
    def raiseerror(self):
        raise forms.ValidationError(
            self.error_messages['password_mismatch'],
            code='password_mismatch',
        )


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['short_desc', 'long_desc', 'private', 'is_encrypted']

class UpdateProfile(forms.ModelForm):

    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ( 'first_name', 'last_name','email',)


class messageForm(forms.ModelForm):
    messagecontent = forms.CharField(required=True)
    newmessagefield = forms.CharField(required=False)
    thekey = forms.CharField(required=False)
    class Meta:
        model = Message
        fields = ('owned_by','sender','messagecontent','thekey','newmessagefield')

class GroupForm(forms.ModelForm):
    class Meta:
        model = ProfileGroup
        fields = ['name', 'members']

class UpdateGroupForm(forms.ModelForm):
    class Meta:
        model = ProfileGroup
        fields = ['name']

class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name']

class UpdateFolder(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ['name', 'reports']


class DecryptMessageForm(forms.ModelForm):
    password = forms.CharField(required=True)
    #message = forms.ModelMultipleChoiceField(queryset=Message.objects.all())

    class Meta:
        model = Message
        fields = ['password']


class SearchForm(forms.Form):
    search = forms.CharField(max_length='128', widget=forms.TextInput(attrs={'cols': 50, 'rows': 1, 'placeholder': "Search for a report"}))
    SEARCH_OPTIONS = (
            ('desc', "Description"),
            ('owner', "Owned By"),
            ('modified_by', "Last Modified By"),
            ('created', "Created",),
            ('modified', "Last Modified"),
        )
    parameter = forms.CharField(widget=forms.Select(choices=SEARCH_OPTIONS))
    datepicker = forms.DateField(widget=SelectDateWidget())

class ReportCommentsForm(forms.ModelForm):
    comment = forms.CharField(required=True, max_length="1000", widget=forms.TextInput(attrs={'cols': 75, 'rows': 2, 'placeholder': "Leave a comment"}))

    class Meta:
        model = ReportComments
        fields = ['comment']

templates/fileshare/changepassword.html
{% extends 'fileshare/base.html' %}


{% block content %}

 <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Password Change</h3>
                    </div>
                    <div class="panel-body">
<form id="changepassword_form" method="post" action="/account/changepassword"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ form.as_p }}

            <!-- Provide a button to click to submit the form. -->
    <p class="text-center"><input type="submit" class="btn btn-success btn-sm" name="submit" value="Change Password" />
    <br \><br \>
     <a href="/account/view">Cancel</a></p>

        </form>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

templates/fileshare/decrypt_message.html
{% extends 'fileshare/base.html' %}


{% block content %}

 <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">View Message</h3>
                    </div>
                    <div class="panel-body">
{% if message %}
                        <p>{{message}}</p>
                        <p>{{message2}}</p>

    {% else %}
                        <form id="decrypt_message_form" method="post"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ form.as_p }}

            <!-- Provide a button to click to submit the form. -->
    <p class="text-center"><input type="submit" class="btn btn-success btn-sm" name="submit" value="Decrypt" />


        </form>

                        {% endif %}


</div>
</div>
</div>
</div>
</div>

{% endblock %}

templates/fileshare/edit_group.html
{% extends 'fileshare/base.html' %}

{% block content %}

{% csrf_token %}
<div class="container">
	<h3>Edit User</h3>
	<div class="panel panel-default">
		<div class="panel-heading"><strong>Groups</strong></div>
		<div class="panel-body">
            <!--still have to write the code that actually updates the info-->
            <!--<form method="post" action="/fileshare/edit_group" enctype="multipart/form-data">-->

            <!--</form>-->
            <!--<br>-->
            <!--<p><font size="3">Groups:</font></p>-->
            <input class="btn btn-success btn-sm" type="submit" value="Save"/>
		</div>
	</div>
    </div>

{% endblock %}

templates/fileshare/edit_user.html
{% extends 'fileshare/base.html' %}

{% block content %}

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading"><strong>Edit User - {{profile.user.username}}</strong></div>
		<div class="panel-body">
			<form method="post" action="/sm_update_user" enctype="multipart/form-data">
				{% csrf_token %}
                    <input type="hidden" name="profile_id" value="{{ profile.id }}">
				<!-- {{ user_form.as_p }} -->
				<p>
					<label for="id_username">Username:</label> <input id="id_username"
						maxlength="150" name="username" type="text" value="{{profile.user.username}}" required /> <span
						class="helptext">Required. 150 characters or fewer.
						Letters, digits and @/./+/-/_ only.</span>
				</p>
				<p>
					<label for="id_email">Email Address:</label> <input id="id_email"
						maxlength="254" name="email" type="email" value="{{profile.user.email}}" />
				</p>
				<p>
					<label for="id_first_name">First Name:</label> <input
						id="id_first_name" maxlength="30" name="first_name" type="text" value="{{profile.user.first_name}}"/>
				</p>
				<p>
					<label for="id_last_name">Last Name:</label> <input
						id="id_last_name" maxlength="30" name="last_name" type="text" value="{{profile.user.last_name}}"/>
				</p>
				<p>
					<div class="form-control-static">
					<label for="id_date_joined">Date Joined:</label>
						 {{profile.user.date_joined}}
					</div>
				</p>
				<p>
					<label for="id_password1">Reset Password:</label> <input
						id="id_password1" name="password1" type="password" />
				</p>
				<p> <!--make sure verification works. check if p1 equals p2-->
					<label for="id_password2">Password confirmation:</label> <input
						id="id_password2" name="password2" type="password" /> <span
						class="helptext">Enter the same password as above, for
						verification.</span>
				</p>
                {% if profile.user.is_active %}
					<input type="checkbox" name='is_active'id="is_active" checked><font size="3">Active</font><br>
				{% else %}
					<input type="checkbox" name='is_active' id="is_active"><font size="3">Active</font><br>
				{% endif %}
				<p>Designates whether this user should be treated as active.
					Unselect this instead of deleting accounts</p>
				{% if profile.user.is_staff %}
					<input type="checkbox" name='is_staff' id="is_staff" checked/><font size="3">Staff Status</font><br>
				{% else %}
					<input type="checkbox" name='is_staff' id="is_staff" /><font size="3">Staff Status</font><br>
				{% endif %}
				<p>Designates whether the user is a site manager</p>
            	<input class="btn btn-success btn-sm" type="submit" value="Save" />
			</form>

		</div>
	</div>
</div>

{% endblock %}


{#{% extends 'fileshare/base.html' %}#}
{##}
{#{% block content %}#}
{##}
{#{% csrf_token %}#}
{#<div class="container">#}
{#	<h3>Edit User</h3>#}
{#	<div class="panel panel-default">#}
{#		<div class="panel-heading"><strong>Permissions</strong></div>#}
{#		<div class="panel-body">#}
{#            <!--still have to write the code that actually updates the info-->#}
{#            <form method="POST" action="/fileshare/edit_user" enctype="multipart/form-data">#}
{#                <input type="checkbox" id="active" value="{{user.is_active}}"><font size = "3">Active</font><br>#}
{#                <p>Designates whether this user should be treated as active. Unselect this instead of deleting accounts</p>#}
{#                <input type="checkbox" id="staff_status"><font size = "3" value ="{{user.is_staff}}">Staff Status</font><br>#}
{#                <p>Designates whether the user is a site manager</p>#}
{#            </form>#}
{#            <br>#}
{#            <!--<p><font size="3">Groups:</font></p>-->#}
{#            <input class="btn btn-success btn-sm" type="submit" value="Save"/>#}
{#		</div>#}
{#	</div>#}
{#    </div>#}
{##}
{#{% endblock %}#}

templates/fileshare/main.html
{% extends 'fileshare/base.html' %}

{% block content %}

<div style="padding-left:40px">
<div class="row">

	<!-- <div style="float:left;width:85%;padding-right: 5px"> -->
	<div class="col-sm-9">
	<h1>Hello, {{ user.username }}!<br><small>You are on your Dashboard</small></h1>


	<div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12" align="right">
						<div class="form-group">
							<form id="s01" class="form-inline" method="POST" action="{% url 'fileshare:search_results' %}">
								{% csrf_token %}
								<div class="input-group">
									{{ search_form.search }}
								</div>
                                <div class="input-group">
									{{ search_form.datepicker }}
								</div>
								<div class="input-group">
									{{ search_form.parameter }}
								</div>
								<button type="submit" class="btn btn-default btn-sm" name="a" value="Search"><span class="glyphicon glyphicon-search"></span></button>

							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="panel-group">
		<div class="panel panel-default">
			<div class="panel-heading"><strong>Your Folders</strong></div>
			<div class="panel-body">
				{% if folders.count == 0 %}
				<i>You have no folders.</i>
				{% else %}

				<table class="table table-hover">
					<tr>
						<th>Name</th>
						<th>Created</th>
					</tr>
					{% for f in folders %}
					<tr>
						<td><a href="{{ f.id }}/view_folder">{{ f.name }}</a></td><td>{{ f.created }}</td>
					</tr>
					{% endfor %}
				</table>
				{% endif %}
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading"><strong>Your Reports</strong></div>
			<div class="panel-body">
				{% if num_reports == 0 %}
				<i>You have no reports.</i>
				{% else %}
				<table class="table table-hover">
					<tr>
						<th></th>
						<th>Title</th>
						<th>Type</th>
						<th>Last Modified By</th>
						<th>Last Modified</th>
						<th>Created</th>
						<th></th>
					</tr>
					{% for r in your_reports %}
					<tr>
						<td>
							{% if r.is_encrypted %}
							<div align="right"><span class="glyphicon glyphicon-lock" style="color:#50aeed"></span></div>
							{% else %}
							{% endif %}
						</td>
						<td>{{ r.short_desc }}</td>
						<td>{% if r.private %}
							<font color="red">Private</font>
							{% else %}
							<font color="green">Public</font>
							{% endif %}</td>
							<td>{{ r.last_modified_by }}</td>
							<td>{{ r.last_modified }}</td>
							<td>{{ r.created }}</td>
							<td>
								<form id="{{ r.short_desc }}" action="{% url 'fileshare:view_report' r.id %}" method="POST">
									{% csrf_token %}
									<button class="btn btn-default btn-sm" type="submit" form="{{ r.short_desc }}" name="action" value="view">
										<span class="glyphicon glyphicon-pencil"></span></button>
									</form>
								</td>
							</tr>
							{% endfor %}
						</table>
						{% endif %}
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading"><strong>Create a New Folder</strong></div>
					<div class="panel-body">
						<form method="POST" action="{% url 'fileshare:main' %}">
							{% csrf_token %}
							{{ folder_form.as_p }}
							<input class="btn btn-primary" type="submit" value="Create Folder">
						</form>
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading"><strong>Other Public Reports</strong></div>
				<div class="panel-body">
					{% if other_reports.count != 0 %}
					<table class="table table-striped">
						<tr>
							<th></th>
							<th>Title</th>
							<th>Owner</th>
							<th>Last Modified By</th>
							<th>Last Modified</th>
							<th>Created</th>
							<th></th>
						</tr>
						{% for r in other_reports %}
						<tr>
							<td>
								{% if r.is_encrypted %}
								<div align="right"><span class="glyphicon glyphicon-lock" style="color:#50aeed"></span></div>
								{% else %}
								{% endif %}
							</td>
							<td>{{ r.short_desc }}</td>
							<td>{{ r.owned_by }}</td>
							<td>{{ r.last_modified_by }}</td>
							<td>{{ r.last_modified }}</td>
							<td>{{ r.created }}</td>
							<td>
								<form id="{{ r.short_desc }}" action="view_report/{{r.id}}" method="POST">
									{% csrf_token %}
									<center><button class="btn btn-default btn-sm" type="submit" form="{{ r.short_desc }}" name="action" value="view"><span class="glyphicon glyphicon-eye-open"></span></button></center>
								</form>
							</td>
						</tr>
						{% endfor %}
					</table>
					{% else %}
				<i>There are no other reports to view.</i>
				{% endif %}
				</div>

			</div>

			<div class="panel panel-default">
				<div class="panel-heading"><strong>Your Groups</strong></div>
				<div class="panel-body">
					{% if user.profile.groups_in.count == 0 %}
					<i>No groups to show</i>
					{% else %}
					<table class="table table-striped">
						<tr>
							<th> Name </th>
							<th> Creator </th>
							<th> Number of Members </th>
						</tr>
						{% for g in user.profile.groups_in.all %}
						<tr>
							<td> <a href="{% url 'fileshare:view_group' g.id %}">{{ g.name }}</a> </td>
							<td>{{ g.creator }}</td>
							<td>{{ g.members.count }}</td>
						</tr>
						{% endfor %}
					</table>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="col-sm-3" style="overflow:scroll;height:800px">
	<!-- <div style="width: 15%;overflow:scroll;"> -->
			{% if activity %}
		<div class="panel panel-default" style="margin-top:110px;margin-right:20px;">
		<div class="panel-heading"><strong>User Activity Feed</strong></div>
			<div class="panel-body">
                {% for a in activity %}
				<div class="well">
					<strong class="primary-font">{{a.description}}</strong>
					<div style="float:right">{{a.time}}</div>
				</div>
				{% endfor %}
			</div>
		</div>
			{% endif %}
	<!-- </div> -->
	</div>
	</div>
</div>

<script>

	function assignjavafunction() {
		var selector = document.getElementById("id_parameter");
		selector.setAttribute("onchange","selectchange()")
		var monthbox = document.getElementById("id_datepicker_month");
		var daybox = document.getElementById("id_datepicker_day");
		var yearbox = document.getElementById("id_datepicker_year");
		monthbox.setAttribute("class","hidden");
			daybox.setAttribute("class","hidden");
			yearbox.setAttribute("class","hidden");
	}

	function selectchange() {
		var selector = document.getElementById("id_parameter");
		var selectedval = selector.value;
		var searchbox = document.getElementById("id_search");
		var monthbox = document.getElementById("id_datepicker_month");
		var daybox = document.getElementById("id_datepicker_day");
		var yearbox = document.getElementById("id_datepicker_year");
		if (selectedval == "desc" || selectedval=="owner" || selectedval=="modified_by") {
			searchbox.setAttribute("class","input-group");
			monthbox.setAttribute("class","hidden");
			daybox.setAttribute("class","hidden");
			yearbox.setAttribute("class","hidden");

		}
		else {
			searchbox.setAttribute("class","hidden");
			monthbox.setAttribute("class","");
			daybox.setAttribute("class","");
			yearbox.setAttribute("class","");

		}

	}


	document.onload = assignjavafunction();
</script>
		{% endblock %}

templates/fileshare/profile.html
<!DOCTYPE html>
<html>

</html>